import OpenAI from "openai";
import type { RequestContext } from "../types/ai.js";

/**
 * Serviço para gestão de atas
 * Implementa as APIs conforme especificado no PRD
 */
export class MinutesService {
  private openaiRouter: OpenAI;

  constructor() {
    const openRouterKey = process.env.OPENROUTER_API_KEY;
    if (!openRouterKey) {
      throw new Error("OPENROUTER_API_KEY environment variable is required");
    }

    this.openaiRouter = new OpenAI({
      baseURL: "https://openrouter.ai/api/v1",
      apiKey: openRouterKey,
      defaultHeaders: {
        "HTTP-Referer": process.env.SITE_URL || "http://localhost:3000",
        "X-Title": process.env.SITE_NAME || "CondoGov API",
      },
    });
  }

  /**
   * Gera ata de assembleia
   */
  async generateMinutesFromAssembly(assemblyId: string, data: any, context: RequestContext) {
    try {
      // 1. Buscar dados da assembleia
      const assembly = await this.getAssemblyFromDatabase(assemblyId, context.companyId);
      if (!assembly) {
        throw new Error("Assembleia não encontrada");
      }

      // 2. Buscar transcrição
      const transcription = await this.getTranscriptionFromDatabase(assemblyId, context.companyId);

      // 3. Gerar ata com IA
      const minutesContent = await this.generateMinutesContent(transcription, assembly, data);

      // 4. Salvar ata
      const minuteId = await this.saveMinute({
        companyId: context.companyId,
        assemblyId,
        title: assembly.title,
        content: minutesContent,
        format: data.format,
        isAutoGenerated: data.aiSummary,
        createdBy: context.userId,
      });

      // 5. Processar assinatura se solicitada
      let document = null;
      if (data.sendForSignature && data.signers) {
        document = await this.createSignatureDocument(minuteId, minutesContent, data.signers, context);
      }

      return {
        assemblyMinuteId: minuteId,
        content: minutesContent,
        document,
      };
    } catch (error) {
      console.error("Error generating minutes from assembly:", error);
      throw error;
    }
  }

  /**
   * Gera ata de gravação
   */
  async generateMinutesFromRecording(recordingId: string, data: any, context: RequestContext) {
    try {
      // 1. Buscar dados da gravação
      const recording = await this.getRecordingFromDatabase(recordingId, context.companyId);
      if (!recording) {
        throw new Error("Gravação não encontrada");
      }

      // 2. Buscar transcrição
      const transcription = await this.getTranscriptionFromRecording(recordingId, context.companyId);

      // 3. Gerar ata com IA
      const minutesContent = await this.generateMinutesContent(transcription, recording, data);

      // 4. Salvar ata
      const minuteId = await this.saveMinute({
        companyId: context.companyId,
        recordingId,
        title: recording.roomName || "Ata de Gravação",
        content: minutesContent,
        format: data.format,
        isAutoGenerated: data.aiSummary,
        createdBy: context.userId,
      });

      return {
        assemblyMinuteId: minuteId,
        content: minutesContent,
      };
    } catch (error) {
      console.error("Error generating minutes from recording:", error);
      throw error;
    }
  }

  /**
   * Lista assembleias disponíveis
   */
  async getAvailableAssemblies(companyId: string, filters: any = {}) {
    try {
      const assemblies = await this.getAssembliesFromDatabase(companyId, filters);
      return assemblies;
    } catch (error) {
      console.error("Error getting available assemblies:", error);
      throw error;
    }
  }

  /**
   * Lista atas
   */
  async getMinutes(companyId: string, filters: any = {}) {
    try {
      const minutes = await this.getMinutesFromDatabase(companyId, filters);
      return minutes;
    } catch (error) {
      console.error("Error getting minutes:", error);
      throw error;
    }
  }

  /**
   * Busca ata específica
   */
  async getMinute(minuteId: string, companyId: string) {
    try {
      const minute = await this.getMinuteFromDatabase(minuteId, companyId);
      return minute;
    } catch (error) {
      console.error("Error getting minute:", error);
      throw error;
    }
  }

  /**
   * Adiciona assinantes
   */
  async addSigners(minuteId: string, signers: any[], context: RequestContext) {
    try {
      const result = await this.saveSigners(minuteId, signers, context);
      return result;
    } catch (error) {
      console.error("Error adding signers:", error);
      throw error;
    }
  }

  /**
   * Envia lembretes
   */
  async sendReminders(minuteId: string, context: RequestContext) {
    try {
      const result = await this.sendRemindersToSigners(minuteId, context);
      return result;
    } catch (error) {
      console.error("Error sending reminders:", error);
      throw error;
    }
  }

  /**
   * Download PDF
   */
  async downloadPdf(minuteId: string, companyId: string) {
    try {
      const minute = await this.getMinuteFromDatabase(minuteId, companyId);
      if (!minute) {
        return null;
      }

      // Gerar PDF (simulado)
      const pdfBuffer = await this.generatePdf(minute.content, minute.title);
      
      return {
        buffer: pdfBuffer,
        filename: `${minute.title.replace(/[^a-zA-Z0-9]/g, '-')}.pdf`,
      };
    } catch (error) {
      console.error("Error downloading PDF:", error);
      throw error;
    }
  }

  /**
   * Gera conteúdo da ata com IA
   */
  private async generateMinutesContent(transcription: any, source: any, options: any): Promise<string> {
    try {
      const systemPrompt = `Você é um especialista em criação de atas de assembleia condominial.

FORMATO: ${options.format}
USAR IA: ${options.aiSummary ? 'Sim' : 'Não'}

Crie uma ata estruturada e profissional baseada na transcrição fornecida.
Use linguagem formal e técnica apropriada para documentos jurídicos.`;

      const userPrompt = `Gere uma ata para:

FONTE: ${source.title || source.roomName}
TRANSCRIÇÃO: ${transcription.transcript || transcription.text}

Formate no formato ${options.format} solicitado.`;

      const completion = await this.openaiRouter.chat.completions.create({
        model: "openai/gpt-5-chat",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.3,
        max_tokens: 4000,
      });

      return completion.choices[0]?.message?.content || "";
    } catch (error) {
      console.error("Error generating minutes content:", error);
      throw error;
    }
  }

  /**
   * Cria documento para assinatura
   */
  private async createSignatureDocument(minuteId: string, content: string, signers: any[], context: RequestContext) {
    try {
      // Gerar PDF
      const pdfBuffer = await this.generatePdf(content, "Ata de Assembleia");
      
      // Converter para base64
      const pdfBase64 = pdfBuffer.toString('base64');
      
      // Criar documento no Autentique (simulado)
      const document = {
        id: `doc_${Date.now()}`,
        name: "Ata de Assembleia",
        signers: signers.map((signer, index) => ({
          ...signer,
          order: index + 1,
        })),
        status: "pending",
        created_at: new Date().toISOString(),
      };

      console.log(`📝 Signature document created (simulated): ${document.id}`);
      
      return document;
    } catch (error) {
      console.error("Error creating signature document:", error);
      throw error;
    }
  }

  /**
   * Gera PDF (simulado)
   */
  private async generatePdf(content: string, title: string): Promise<Buffer> {
    // Simular geração de PDF
    const mockPdfContent = `%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj

2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj

3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
>>
endobj

4 0 obj
<<
/Length 44
>>
stream
BT
/F1 12 Tf
72 720 Td
(${title}) Tj
ET
endstream
endobj

xref
0 5
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000204 00000 n 
trailer
<<
/Size 5
/Root 1 0 R
>>
startxref
297
%%EOF`;

    return Buffer.from(mockPdfContent);
  }

  /**
   * Salva ata no banco
   */
  private async saveMinute(data: any): Promise<string> {
    const minuteId = `minute_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;
    console.log(`💾 Minute saved (simulated): ${minuteId}`);
    return minuteId;
  }

  /**
   * Salva assinantes no banco
   */
  private async saveSigners(minuteId: string, signers: any[], context: RequestContext) {
    console.log(`💾 Signers saved (simulated): ${signers.length} signers for minute ${minuteId}`);
    return {
      minuteId,
      signers: signers.map((signer, index) => ({
        id: `signer_${Date.now()}_${index}`,
        ...signer,
        status: "pending",
        created_at: new Date().toISOString(),
      })),
    };
  }

  /**
   * Envia lembretes para assinantes
   */
  private async sendRemindersToSigners(minuteId: string, context: RequestContext) {
    console.log(`📧 Reminders sent (simulated): for minute ${minuteId}`);
    return {
      minuteId,
      remindersSent: 3,
      status: "sent",
    };
  }

  /**
   * Busca assembleia no banco
   */
  private async getAssemblyFromDatabase(assemblyId: string, companyId: string): Promise<any> {
    // Simular busca
    return {
      id: assemblyId,
      title: "Assembleia Ordinária - Janeiro 2025",
      description: "Assembleia para aprovação de orçamento",
      scheduled_date: "2025-01-25T14:00:00Z",
      location: "Salão de festas",
      status: "realizada",
      client_id: 1,
      company_id: companyId,
    };
  }

  /**
   * Busca gravação no banco
   */
  private async getRecordingFromDatabase(recordingId: string, companyId: string): Promise<any> {
    // Simular busca
    return {
      id: recordingId,
      room_id: "assembly-123",
      room_name: "Assembleia Janeiro 2025",
      file_path: "/recordings/assembly_123.mp3",
      file_size: 15728640,
      duration: 630,
      status: "completed",
      company_id: companyId,
    };
  }

  /**
   * Busca transcrição no banco
   */
  private async getTranscriptionFromDatabase(assemblyId: string, companyId: string): Promise<any> {
    // Simular busca
    return {
      id: `trans_${assemblyId}`,
      assembly_id: assemblyId,
      transcript: "Transcrição completa da assembleia...",
      status: "completed",
      confidence: 0.91,
    };
  }

  /**
   * Busca transcrição de gravação no banco
   */
  private async getTranscriptionFromRecording(recordingId: string, companyId: string): Promise<any> {
    // Simular busca
    return {
      id: `trans_${recordingId}`,
      recording_id: recordingId,
      text: "Transcrição completa da gravação...",
      status: "completed",
      confidence: 0.91,
    };
  }

  /**
   * Busca assembleias no banco
   */
  private async getAssembliesFromDatabase(companyId: string, filters: any): Promise<any[]> {
    // Simular busca
    return [
      {
        id: 1,
        title: "Assembleia Ordinária - Janeiro 2025",
        description: "Assembleia para aprovação de orçamento",
        scheduled_date: "2025-01-25T14:00:00Z",
        location: "Salão de festas",
        status: "realizada",
        client_id: 1,
      },
      {
        id: 2,
        title: "Assembleia Extraordinária - Fevereiro 2025",
        description: "Assembleia para eleição de síndico",
        scheduled_date: "2025-02-15T14:00:00Z",
        location: "Virtual",
        status: "agendada",
        client_id: 1,
      },
    ];
  }

  /**
   * Busca atas no banco
   */
  private async getMinutesFromDatabase(companyId: string, filters: any): Promise<any[]> {
    // Simular busca
    return [
      {
        id: 1,
        title: "Ata da Assembleia Ordinária - Janeiro 2025",
        content: "Conteúdo da ata...",
        status: "finalizada",
        is_auto_generated: true,
        created_at: "2025-01-25T16:00:00Z",
        assembly: {
          id: 1,
          title: "Assembleia Ordinária - Janeiro 2025",
          scheduled_date: "2025-01-25T14:00:00Z",
        },
        signatures: {
          total: 3,
          signed: 3,
          pending: 0,
        },
      },
    ];
  }

  /**
   * Busca ata específica no banco
   */
  private async getMinuteFromDatabase(minuteId: string, companyId: string): Promise<any> {
    // Simular busca
    return {
      id: minuteId,
      title: "Ata da Assembleia Ordinária - Janeiro 2025",
      content: "# ATA DA ASSEMBLEIA ORDINÁRIA\n\n## 1. ABERTURA\n...",
      status: "finalizada",
      is_auto_generated: true,
      created_at: "2025-01-25T16:00:00Z",
      assembly: {
        id: 1,
        title: "Assembleia Ordinária - Janeiro 2025",
        scheduled_date: "2025-01-25T14:00:00Z",
      },
      signatures: [
        {
          id: 1,
          name: "João Silva",
          email: "joao@condominio.com",
          role: "Síndico",
          status: "assinado",
          signed_at: "2025-01-26T10:30:00Z",
        },
        {
          id: 2,
          name: "Maria Santos",
          email: "maria@condominio.com",
          role: "Subsíndica",
          status: "assinado",
          signed_at: "2025-01-26T11:00:00Z",
        },
      ],
    };
  }
}
